-- Local dev data only (npm run dev:setup). Never run this against the real database.
-- The "sample:*" links are generated by worker/src/dev/samples.js and only work with DEV_MODE = "true".

DELETE FROM calendars;
DELETE FROM feed_cache;
INSERT INTO calendars (name, color, url, source, owner, default_on, is_shift, sort_order, created_at, updated_at) VALUES
  ('Student Work Schedule', '#B07A00', 'sample:work',   'outlook', 'SCSM office',  1, 1, 1, 0, 0),
  ('School Events',         '#2F5BD3', 'sample:school', 'outlook', 'Dean''s office', 1, 0, 2, 0, 0),
  ('Club Events',           '#1B7F52', 'sample:clubs',  'google',  'Parijat Das',  1, 0, 3, 0, 0),
  ('Social Media',          '#983BAE', 'sample:social', 'outlook', '',             0, 0, 4, 0, 0);

INSERT OR IGNORE INTO staff (email, added_at, added_by) VALUES
  ('staff@marist.edu', 0, 'seed'),
  ('elina@marist.edu', 0, 'seed');
