-- Local dev data only (npm run dev:setup). Never run this against the real database.
-- The "sample:*" links are generated by worker/src/dev/samples.js and only work with DEV_MODE = "true".

DELETE FROM calendars;
DELETE FROM feed_cache;
INSERT INTO calendars (name, color, url, source, owner, default_on, audience, sort_order, created_at, updated_at) VALUES
  ('Club & School Events',  '#E0475B', 'sample:clubs',  'other',   'Parijat Das',    1, 'public', 1, 0, 0),
  ('School Events',         '#5B4FB3', 'sample:school', 'outlook', 'Dean''s office', 1, 'public', 2, 0, 0),
  ('Social Media',          '#1E8E62', 'sample:social', 'outlook', '',               0, 'staff',  3, 0, 0);

DELETE FROM staff WHERE added_by = 'seed';
INSERT INTO staff (email, name, role, access_until, added_at, added_by) VALUES
  ('staff@marist.edu',     'Sam Rivera',   'staff',     NULL,         0, 'seed'),
  ('elina@marist.edu',     'Elina Park',   'assistant', '2026-12-18', 0, 'seed'),
  ('admin@marist.edu',     'Alex Morgan',  'admin',     NULL,         0, 'seed');
